import ast
from typing import List
from app.models.diagnostic import Diagnostic
from app.analyzers.scope import VariableScopeVisitor


class UnusedVariableAnalyzer:
    """
    Analyzes AST for unused variables utilizing Scope tracking.
    """

    def analyze(self, scope_visitor: VariableScopeVisitor) -> List[Diagnostic]:
        diagnostics = []
        # Return diagnostics already generated by scope visitor for unused variables
        for diag in scope_visitor.diagnostics:
            if diag.category == "unused-variable":
                diagnostics.append(diag)
        return diagnostics


def analyze_unused_variables(tree: ast.AST, scope_visitor: VariableScopeVisitor) -> List[Diagnostic]:
    analyzer = UnusedVariableAnalyzer()
    return analyzer.analyze(scope_visitor)
